### ISSUE TITLE
Add a `limit` parameter to the query

### ISSUE THREAD

**Issue by joshuabaker** [aelvan/Similar-Craft#1]
Add a `limit` parameter to the query. Something like the below-pasted.

``` php
if (isset($data['limit'])) {
    $query->limit($data['limit']);
}
```

Other options would be helpful too (e.g. `offset`).

**Comment by aelvan** [comment]
You can use both `limit` and `offset` (and any other parameters that are available to an ElementCriteriaModel) by creating an `ElementCriteriaModel` and passing it in as the `criteria` parameter, like so:

```
{% set limitCriteria = craft.entries.limit(4) %}
{% set similarEntriesByTags = craft.similar.find({ element: entry, context: entry.tags, criteria: limitCriteria }) %}
```

**Comment by joshuabaker** [comment]
I understand now. Didn’t realise because it’s slightly different from the Craft paradigm. Thank you. :grin:
