### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ryankauk** [aelvan/Similar-Craft#2]
Hey there, I saw this plugin and it would be perfect to use However when I use what was suggested

```
{% set ids = entry.tags.ids() | merge(entry.categories.ids()) %}
{% set limitCriteria = craft.entries.limit(4) %}
{% set similarEntriesByTagsAndCategories = craft.similar.find({ element: entry, context: ids, criteria: limitCriteria }) %}
<ul>
    {% for similarEntry in similarEntriesByTagsAndCategories %}
        <li>{{ similarEntry.title }} {{ similarEntry.count }} </li>
    {% endfor %}
</ul>
```

But when I use that, I get an internal server error. I have it placed in the entry template of a section. Am I missing something?

**Comment by aelvan** [comment]
No, that should work. If you turn devMode on, what is the error that Craft returns?

**Comment by ryankauk** [comment]
Nvm, I made a dumb mistake and used the entry.categories when I should've used the right handle for my category field. Thanks anyway!

**Comment by aelvan** [comment]
Great, np.
