### ISSUE TITLE
Internal Server Error with example(s)

### ISSUE THREAD

**Issue by green-plastic** [aelvan/Similar-Craft#5]
Hi,

I just copied and pasted your exact examples.

I get this:

```
Internal Server Error
Required parameter element was not supplied to craft.similar.find.
```

Does element have to be a specific entry? Sorry, I'm new to Craft and if this is the case, it's not apparent.

**Comment by aelvan** [comment]
Yes, element has to be an entry (or some other kind of element; asset, category, commerce product, etc).

Can you add some of the code you're using, preferably with some context, and I'll have a look at it.

**Comment by green-plastic** [comment]
This is the code I used.

```
{% set entry = craft.entries.id(4) %}
{% set similarEntriesByTags = craft.similar.find({ element: entry, context: entry.tags }) %}
<ul>
    {% for similarEntry in similarEntriesByTags %}
        <li>{{ similarEntry.title }} ({{ similarEntry.count }} tags in common)</li>
    {% endfor %}
</ul>
```

**Comment by aelvan** [comment]
Try doing `{% set entry = craft.entries.id(4).first() %}` and let me know if that helps.

**Comment by green-plastic** [comment]
I got the same internal server error.

**Comment by aelvan** [comment]
I get this error if I don't pass an existing element as the element parameter. Are you sure that you actually have an entry with id=4? If you do `{{ entry.title }}` after setting `entry`, does it return the title of the entry you're trying to get?

**Comment by green-plastic** [comment]
Well that was it! I swear I had an entry with id 4. Oh well! Thanks for your help.
