### ISSUE TITLE
Craft 3 port?

### ISSUE THREAD

**Issue by khalwat** [aelvan/Similar-Craft#8]
Is a Craft 3 port in the works? I'm almost done converting a site to Craft 3, and it uses this plugin.

**Comment by aelvan** [comment]
@mildlygeeky asked to take over the development of the plugin some weeks back, and I told him he could. I think he needed it fast, so maybe he has something to share with you by now. :)

**Comment by khalwat** [comment]
Well, do ya @mildlygeeky ?

**Comment by mildlygeeky** [comment]
Hey! I do - I’ve been tied up on another project, so haven’t finished it, but am probably about 75% done. When do you need it for @khalwat?

**Comment by khalwat** [comment]
@mildlygeeky 5 days ago :)

**Comment by khalwat** [comment]
Ported: https://github.com/nystudio107/craft-similar
